-- Production certification repair: deny anonymous direct access to
-- public.profiles and keep public reads on public.public_profiles.
--
-- Supabase CLI was unavailable in this environment, so this forward-only
-- migration was created manually with a new timestamp instead of generated by
-- `supabase migration new`.
--
-- Verification SQL after applying:
--   set local role anon;
--   select id from public.profiles limit 1; -- must fail with permission denied
--   select username from public.public_profiles limit 1; -- must succeed
--   reset role;
--   set local role authenticated;
--   select id from public.profiles where id = auth.uid(); -- self rows only under RLS
--   reset role;
--
-- Rollback, only if the deployment must be reverted:
--   grant select on table public.profiles to anon;
--   drop policy if exists "Authenticated users can read allowed profiles" on public.profiles;
--   create policy "Profiles are viewable by everyone" on public.profiles for select using (true);
--   alter view public.public_profiles set (security_invoker = true);

begin;

alter view public.public_profiles set (security_invoker = false);

comment on view public.public_profiles is
  'Curated public profile read surface. Anonymous clients may read only this view; direct public.profiles access is denied.';

revoke all privileges on table public.profiles
from anon;

do $$
declare
  profile_column record;
begin
  for profile_column in
    select column_name
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'profiles'
  loop
    execute format(
      'revoke select (%1$I), insert (%1$I), update (%1$I), references (%1$I) on table public.profiles from anon',
      profile_column.column_name
    );
  end loop;
end;
$$;

drop policy if exists "Profiles are viewable by everyone" on public.profiles;

drop policy if exists "Authenticated users can read allowed profiles" on public.profiles;
create policy "Authenticated users can read allowed profiles"
  on public.profiles for select
  to authenticated
  using (
    id = (select auth.uid())
    or private.current_user_can_moderate()
    or (
      is_private = false
      and suspended_at is null
      and banned_at is null
    )
  );

grant select on table public.public_profiles
to anon, authenticated;

grant select on table public.profiles
to authenticated, service_role;

commit;
